//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.TranslatorServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Word", Namespace="http://schemas.datacontract.org/2004/07/TranslatorService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.TranslatorServiceReference.EnglishWord))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client.TranslatorServiceReference.RussianWord))]
    public partial class Word : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnglishWord", Namespace="http://schemas.datacontract.org/2004/07/TranslatorService")]
    [System.SerializableAttribute()]
    public partial class EnglishWord : Client.TranslatorServiceReference.Word {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.TranslatorServiceReference.RussianWord[] TranslationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.TranslatorServiceReference.RussianWord[] Translations {
            get {
                return this.TranslationsField;
            }
            set {
                if ((object.ReferenceEquals(this.TranslationsField, value) != true)) {
                    this.TranslationsField = value;
                    this.RaisePropertyChanged("Translations");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RussianWord", Namespace="http://schemas.datacontract.org/2004/07/TranslatorService")]
    [System.SerializableAttribute()]
    public partial class RussianWord : Client.TranslatorServiceReference.Word {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.TranslatorServiceReference.EnglishWord[] TranslationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.TranslatorServiceReference.EnglishWord[] Translations {
            get {
                return this.TranslationsField;
            }
            set {
                if ((object.ReferenceEquals(this.TranslationsField, value) != true)) {
                    this.TranslationsField = value;
                    this.RaisePropertyChanged("Translations");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TranslatorServiceReference.ITranslateService")]
    public interface ITranslateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslateService/AddWord", ReplyAction="http://tempuri.org/ITranslateService/AddWordResponse")]
        string AddWord(Client.TranslatorServiceReference.Word wrd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslateService/UpdateWord", ReplyAction="http://tempuri.org/ITranslateService/UpdateWordResponse")]
        string UpdateWord(Client.TranslatorServiceReference.Word wrd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslateService/RemoveWord", ReplyAction="http://tempuri.org/ITranslateService/RemoveWordResponse")]
        string RemoveWord(Client.TranslatorServiceReference.Word wrd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslateService/GetTranslation", ReplyAction="http://tempuri.org/ITranslateService/GetTranslationResponse")]
        Client.TranslatorServiceReference.Word[] GetTranslation(Client.TranslatorServiceReference.Word wrd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslateService/WakeUp", ReplyAction="http://tempuri.org/ITranslateService/WakeUpResponse")]
        void WakeUp();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITranslateServiceChannel : Client.TranslatorServiceReference.ITranslateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TranslateServiceClient : System.ServiceModel.ClientBase<Client.TranslatorServiceReference.ITranslateService>, Client.TranslatorServiceReference.ITranslateService {
        
        public TranslateServiceClient() {
        }
        
        public TranslateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TranslateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddWord(Client.TranslatorServiceReference.Word wrd) {
            return base.Channel.AddWord(wrd);
        }
        
        public string UpdateWord(Client.TranslatorServiceReference.Word wrd) {
            return base.Channel.UpdateWord(wrd);
        }
        
        public string RemoveWord(Client.TranslatorServiceReference.Word wrd) {
            return base.Channel.RemoveWord(wrd);
        }
        
        public Client.TranslatorServiceReference.Word[] GetTranslation(Client.TranslatorServiceReference.Word wrd) {
            return base.Channel.GetTranslation(wrd);
        }
        
        public void WakeUp() {
            base.Channel.WakeUp();
        }
    }
}
